# Generated by Django 3.1.4 on 2021-03-12 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isTeacher',
            field=models.BooleanField(default=False),
        ),
    ]
